### ISSUE TITLE
MapTrackingService Looper 확인 필요

### ISSUE THREAD

**Issue by csi111** [boostcampth/boostcamp3_F#71]
onCreate에서 호출되는 해당 코드의 Looper가 MainThread의 Looper로 확인되어집니다. 의도한 부분이 맞는지 확인해주세요

```
try {
            mFusedLocationClient.requestLocationUpdates(locationRequest, locationCallback, Looper.myLooper())

        } catch (ex: java.lang.SecurityException) {
            Log.i(TAG, "fail to request location update, ignore", ex)
        } catch (ex: IllegalArgumentException) {
            Log.d(TAG, "network provider does not exist, " + ex.message)
        }

```

**Comment by myung6024** [comment]
데이터를 받아 UI를 변화시키는 작업을 하므로 MainThread에서 돌아야 한다고 생각을 했습니다. 하지만 자료를 찾아보니 공식 문서에서 FusedLocationClient과 LocationCallback을 사용하면 해당 부분을 null 처리해도 된다는 것을 알게 되었습니다. 감사합니다!

**Comment by myung6024** [comment]
` [5d96923](/boostcampth/boostcamp3_F/pull/85/commits/5d9692349fe9246b683baeb497bfa6ecbc8c6538)`
